name: trivy scan

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      runs-on:
        type: string
        required: false
        default: ubuntu-latest
      scan-type:
        type: string
        required: false
        default: fs
        description: 'The type of scan: fs (filesystem), image, repo, etc.'
      image-ref:
        type: string
        required: false
        description: 'The image to scan (required if scan-type is image)'
      scan-ref:
        type: string
        required: false
        default: '.'
        description: 'The path or reference to scan (default: . for filesystem)'

jobs:
  trivy-scan:
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      # - name: full scan with Trivy
      #   uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
      #   env:
      #     TRIVY_DEBUG: true
      #   with:
      #     scan-type: ${{ inputs.scan-type }}
      #     image-ref: ${{ inputs.image-ref }}
      #     scan-ref: ${{ inputs.scan-ref }}
      #     format: 'sarif'
      #     output: 'trivy-results.sarif'
      #     exit-code: '0'
      # - name: fail with high critical
      #   uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
      #   with:
      #     scan-type: ${{ inputs.scan-type }}
      #     image-ref: ${{ inputs.image-ref }}
      #     scan-ref: ${{ inputs.scan-ref }}
      #     format: 'table'
      #     severity: 'HIGH,CRITICAL'
      #     output: 'trivy-results.txt'
      #     exit-code: '1'
      # - name: job summary
      #   run: |
      #     # step summary
      #     echo '```' >> $GITHUB_STEP_SUMMARY
      #     cat trivy-results.txt >> $GITHUB_STEP_SUMMARY
      #     echo '```' >> $GITHUB_STEP_SUMMARY
      # - name: Upload Trivy results to Security tab
      #   if: always()
      #   uses: github/codeql-action/upload-sarif@45cbd0c69e560cd9e7cd7f8c32362050c9b7ded2 # v4.32.2
      #   with:
      #     sarif_file: 'trivy-results.sarif'
